# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "Dávid Molnár"

# A description of your site for social meta tag, search engines, and feed.xml
description: "Dávid Molnár on Programming, UX, Design, Productivity, .NET, Azure and more."

keywords: "Computer, .NET, C#, Microsoft, Weblog, Germany, Munich, ASP.NET, Azure, Cloud, Productivity, UX, User Experience, Design, ASP.NET, Programming, Javascript"

# Tagline near the site title
tagline: "Thoughts, stories and ideas."

site_name: "Dávid Molnár Blog"

# The subpath of your site, e.g. /blog, for generating urls
baseurl: 

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://blog.mdavid626.com"

# Site navigation - each item must have a title and a url.
navigation:
- text: Home
  url: /
- text: About
  url: /about/
- text: Archives
  url: /tags/

# The shortname for your Disqus site to enable comments.
disqus: david-molnar-blog

# Author information - author info at the bottom of the post
author_name: "Dávid Molnár"
author_bio: "Dávid is a skilled Full-Stack .NET Developer."
author_url:  "https://mdavid626.com"
author_location: "Munich, Germany"
author_image: /images/authorimage.jpg?v=2

# Sidebar Add banner
#banner_url: "http://justgoodthemes.com"
#banner_image: images/banner.jpg

# Sidebar newsletter widget - add your form action url for MailChimp signup form here
mailchimp_url: "//github.us15.list-manage.com/subscribe?u=d0be1a7297837ca479e103216&id=f960dea6fd"

# Social links in the site footer
twitter_username: "mdavid626"
facebook_username: "mdavid626"
googleplus_username: "+mdavid626"
github_username: "mdavid626"
#codepen_username: "mdavid626"
dribbble_uername: "mdavid626"
medium_username: "@mdavid626"
instagram_username: "mdavid626"
pinterest_username: "mdavid626"
linkedin_username: "mdavid626"
#weibo_username: "username"

# Facebook
fb_appid: "263003530833663"
fb_admins: "mdavid626"

# http://jekyllrb.com/docs/pagination/
paginate: 5
paginate_path: '/blog/page:num/'
plugins: [jekyll-paginate]

permalink: pretty
markdown: kramdown
kramdown:
    auto_ids: false
